---
name: Bandit and SonarQube

"on":
  push: null
  pull_request: null
  schedule:
    - cron: '30 7 * * 3'
  workflow_dispatch: true

jobs:
  bandit:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@ab1d87dfccc5a0ffab88be3aaac6ffe35c10d6cd
        with:
          exit_zero: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          excluded_paths: test/
          level: MEDIUM
          confidence: HIGH

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=mxcube-tes
            -Dsonar.projectKey=Phantominumm_mxcubeweb
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
